package Tables;
// Generated Jun 20, 2022 5:55:05 PM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

/**
 * Faculties generated by hbm2java
 */
@Entity
public class Faculties  implements java.io.Serializable {
    @Id 
    private String FacultyCode;
     private String FacultyName;
 @OneToMany(mappedBy = "DepartmentFacultyCode")
 private List<Departments>department;

    public String getFacultyCode() {
        return FacultyCode;
    }

    public void setFacultyCode(String FacultyCode) {
        this.FacultyCode = FacultyCode;
    }

    public String getFacultyName() {
        return FacultyName;
    }

    public void setFacultyName(String FacultyName) {
        this.FacultyName = FacultyName;
    }

    public List<Departments> getDepartment() {
        return department;
    }

    public void setDepartment(List<Departments> department) {
        this.department = department;
    }
 
}


