package Tables;
// Generated Jun 20, 2022 5:55:05 PM by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;

/**
 * Teachers generated by hbm2java
 */
@Entity
public class Teachers  implements java.io.Serializable {
    @Id
    private String teacherId;
     private String gender;
     private String passwd;
     private String teacherName;
     @ManyToMany
    @JoinTable(name = "TeacherCourseRelation",joinColumns={@JoinColumn(name = "teacherId")},inverseJoinColumns = {@JoinColumn(name = "CourseCode")})
     List<Course>Courses;

    public String getTeacherId() {
        return teacherId;
    }

    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getPasswd() {
        return passwd;
    }

    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    public String getTeacherName() {
        return teacherName;
    }

    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }

    public List<Course> getCourses() {
        return Courses;
    }

    public void setCourses(List<Course> Courses) {
        this.Courses = Courses;
    }

}


